### ISSUE TITLE
When trying to reinstall this addon in Blender 3.4 I get this error

### ISSUE THREAD

**Issue by gkcc0625** [JulienHeijmans/quicksnap#3]

**Comment by JulienHeijmans** [comment]
Hey ! I can see that you removed the description, did you manage to get around the issue?
I remember seeing that bug before, but I thought that I fixed it. 

If you still have it, could you copy paste the last few lines in the console ? (Open the system console via the menu **Window > Toggle System Console**)

**Comment by JulienHeijmans** [comment]
Closing since there are no responses from the reporter.
