### ISSUE TITLE
The story with the local mode is not over

### ISSUE THREAD

**Issue by Oxicid** [JulienHeijmans/quicksnap#33]
In local mode, when the neighboring collection is hidden, an error pops up - Object 'SM_House_2_Periphery.001' can't be hidden because it is not in View Layer 'View Layer'! 

https://drive.google.com/file/d/1lnyVSRabo9Bzz0JDbFnLyUKQUxW_d_J8/view?usp=sharing

**Comment by JulienHeijmans** [comment]
Hey!
Thank you for the repro scene, I must have been missing something.
I will have a look at it this weekend and push a fix.

**Comment by JulienHeijmans** [comment]
It should be fixed it you update to the latest version.
Thank you for reporting the issue!

**Comment by Oxicid** [comment]
The problem is gone
