### ISSUE TITLE
Cannot be installed on blender version 3.3.1

### ISSUE THREAD

**Issue by ayyubmuhammad21** [JulienHeijmans/quicksnap#37]
QuickSnap error when I enabled

**Comment by JulienHeijmans** [comment]
Hey, what error?

**Comment by ayyubmuhammad21** [comment]
when I want to enable this addons, I get an error notification
[image: image.png]

*Best Regards,*

Muhammad Ayyub
+6281351371883
Tanjung Selor, Kabupaten Bulungan, Kalimantan Utara, 77212
INDONESIA


Pada tanggal Min, 6 Nov 2022 pukul 18.45 Julien Heijmans <
***@***.***> menulis:

**Comment by JulienHeijmans** [comment]
Hey, I am sorry but I cannot see the image if you send it via an email. Click on the link "[view it on GitHub]" at the end of the mail, and send the image on github.

I tried installing the addon on 3.3.1 here and had no problem, so I need to know exactly what's your error to be able to fix it.

**Comment by ayyubmuhammad21** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/86995024/200173363-a0982e86-d732-4c3f-882e-2bba4d125ac0.png)

I hope you can see it

**Comment by ayyubmuhammad21** [comment]
hello, I just found the solution. the addons successfully installed if using a zip file. I've tried it.

Thankyou for the response
