### ISSUE TITLE
Does not snap from the camera in the orthographic type.

### ISSUE THREAD

**Issue by Oxicid** [JulienHeijmans/quicksnap#38]
Another find :) https://drive.google.com/file/d/1iVe8QLDuP0ZmysoujoisqwHE2Ayd2Ctp/view?usp=sharing https://drive.google.com/file/d/1Tp2IWFGPa_5vBi9IrUmiRNQOKsz_ZtC5/view?usp=sharing

**Comment by JulienHeijmans** [comment]
Can you try the latest main version? I think it hsould be fixed there.
To get it:
![5efcff3ee0f7cd8323de7bf38da2b422](https://user-images.githubusercontent.com/35562774/201471538-51d4b528-4655-40b2-b68a-4d9252c1d033.gif)

**Comment by JulienHeijmans** [comment]
Arg no, I only fixed it for the origin point selection.

**Comment by JulienHeijmans** [comment]
Alright, now it should be good. I noticed some other issues with pivot points of objects behind the camera that were still snap origins/targets.

**Comment by Oxicid** [comment]
Everything works great! Initially I wanted to report only that in the orthogonal camera objects do not snap, and accidentally found a bug with the points. I like the fact that you quickly find a solution, not like game developers who can't fix annoying little bugs for years :)
