### ISSUE TITLE
Does not work hotkeys 

### ISSUE THREAD

**Issue by MrRomaninTR** [JulienHeijmans/quicksnap#39]
I installed addon, used Ctrl+Shift+V tool is enabled. But then i click hotkey 2 or 3 and it doesn't switch, it stay on "for vertex".

**Comment by JulienHeijmans** [comment]
Hi, were you using the numpad?

Could you get the latest 'Main' version, by doing like in this video:
![5efcff3ee0f7cd8323de7bf38da2b422](https://user-images.githubusercontent.com/35562774/201471277-06a57251-34bd-4e94-8ebf-c21710bc4dd1.gif)

And then tell me if you still have the issue?

**Only if you do have the issue**, I would like you to do some manipulations:
* Open the console (Windows - Open System Console)
* Enable the QuickSnapTool (Ctrl+Shift+V)
* Press CTRL+SHIFT+TAB, 2 times. You should see this in the console:
```
[INFO] 2022-11-12 12:13:05,306 QuickSnap: Setting logger level to: INFO.
[INFO] 2022-11-12 12:13:05,307 Use Ctrl+Shift+TAB when QuickSnap is enabled to change debug level.
[DEBUG] 2022-11-12 12:13:05,798 QuickSnap: Setting logger level to: DEBUG.
[DEBUG] 2022-11-12 12:13:05,798 Use Ctrl+Shift+TAB when QuickSnap is enabled to change debug level.
```
* Right click to disable the tool.
* Enable the tool again, then press multiple times on the 2 or 3 key
* Copy paste here the text that displays in the logs when you press the button... Hopefully it hsould be something like: 
```
[DEBUG] 2022-11-12 12:15:18,505 Input key: TWO
[DEBUG] 2022-11-12 12:15:18,655 Input key: TWO
[DEBUG] 2022-11-12 12:15:18,806 Input key: TWO
[DEBUG] 2022-11-12 12:15:18,964 Input key: TWO
[DEBUG] 2022-11-12 12:15:19,106 Input key: TWO
```
You can then disable the debug in the tool, by presseing Ctrl+Shift+Tab once when the tool is enabled. It should print this in the console: `QuickSnap: Disabling debug. Use Ctrl+Shift+TAB when QuickSnap is enabled to change debug level.`

**Comment by MrRomaninTR** [comment]
Thank you, i installed Main version and it works now.

**Comment by JulienHeijmans** [comment]
Great to know, thank you for reporting your issue!
