### ISSUE TITLE
Error when there is no active object among the selected objects.

### ISSUE THREAD

**Issue by Oxicid** [JulienHeijmans/quicksnap#41]
Everything works fine, even when an error occurs, you just need to set ob.select_set(True) to some object from the list of selected objects, or there is another option that eliminates the need for the active object 

https://drive.google.com/file/d/1NJ_Aklxg018uxzskh4OuYyCw9A6JE6C6/view?usp=sharing

**Comment by JulienHeijmans** [comment]
Can you tell me how the user can have objects selected but no active objects? Wondering how this can happen naturally.

**Comment by Oxicid** [comment]
The video I attached earlier shows how you can cause this error, you have to delete the active object and then select objects via box select, but there is no active object among them. Basically there is no problem, I encountered this only once, there is no need to fix it.

**Comment by JulienHeijmans** [comment]
Ah, yes, indeed, I answered a bit quicky without noticing the video, I thought it was a blender file for repro.
Thank you for hte PR!
