### ISSUE TITLE
Can you add a function?

### ISSUE THREAD

**Issue by sexfio** [JulienHeijmans/quicksnap#47]
For example, if a cube is above a plane, I want to drag a point on the lowermost surface of the cube, and press Z ,then "display the intersection point on the plane", so that I can make it fit vertically

**Comment by JulienHeijmans** [comment]
You can constrain the translation to a specific axis already, just the way you are explaining it.
If you start snapping from the lowermost surface of a cube, then press Z and pick a point of the plane (a corner, or face/edge center), it will move the cube vertically and be aligned with the plane.

![accbed0e3f1785053757cd88000897d5](https://user-images.githubusercontent.com/35562774/206197457-bdf7360d-3a26-42ff-8e26-8bcacdd826c4.gif)

**Comment by sexfio** [comment]
btw, do you know the command to switch blender's language to Chinese?   I can't find it

**Comment by JulienHeijmans** [comment]
Cool.
For the language it's in the Preferences > Interface > Translation

**Comment by sexfio** [comment]
I know. What I want to ask is how to write a plug-in in Python to implement it
