### ISSUE TITLE
Shader compile error with Blender 3.5 / 3.6 I'll get this message.

### ISSUE THREAD

**Issue by nurb2kea** [JulienHeijmans/quicksnap#50]
Hi,
when updating to blender 3.5 / 3.6 the addon will still be enabled but not working.
When switching it on/off you'll get the below messages.

![Screenshot 2023-02-16 at 1 37 05 pm](https://user-images.githubusercontent.com/57676085/219367084-b67c4fdd-2eb0-41c2-9bee-8a5a24e61301.jpg)

![Screenshot 2023-02-16 at 1 32 11 pm](https://user-images.githubusercontent.com/57676085/219366175-11790829-a67f-4e8b-9e4e-cee80da7bbb1.jpg)

**Comment by JulienHeijmans** [comment]
Thank you for reporting the issue! :) 
Those are not officially supported yet, but I will have a look when I have time and hopefully fix the issue soon.

**Comment by JulienHeijmans** [comment]
Hey! I just tested the addon with both 3.5 and 3.6 without issue.
Could you maybe try to remove the addon from your blender preferences, then download the zip of the last version of the addon ([Here](https://github.com/JulienHeijmans/quicksnap/archive/refs/tags/1_4_1.zip)), and then in blender>Preferences>Add-ons window, click on `Install...` and you pick the zip file of the addon you just downloaded.

If it still does not work, could you tell me a bit about your setup, do you use Windows, Mac or Linux?
Maybe you could open the console (Menu Window>Toggle system console) and copy/paste here the details of the Shader Compile Error.

Thank you :)

**Comment by nurb2kea** [comment]
Hi,

I uninstalled it, rebooted blender and tried to install the zip from your last message.
I install my plugins via/into the preferences folder.
- My System is MacOS 13.2.1 --INTEL-- 
- Blender 3.5a/b & 3.6a 
- METAL for Render & Backend GPU with a AMD Radeon Pro... (see system screenshot below)

Started it via Terminal and this is the message from terminal:
![Screenshot 2023-02-17 at 7 14 09 pm](https://user-images.githubusercontent.com/57676085/219745756-95272e40-ed42-47d6-82b1-343e20ba2ac6.jpg)


![Screenshot 2023-02-17 at 7 07 26 pm](https://user-images.githubusercontent.com/57676085/219743044-19e71655-0981-4283-9d3c-8eb201f724c1.jpg)

![Screenshot 2023-02-17 at 7 03 24 pm](https://user-images.githubusercontent.com/57676085/219742085-81295cab-c218-4c51-86e1-d54bd421df26.jpg)


![Screenshot 2023-02-17 at 6 58 57 pm](https://user-images.githubusercontent.com/57676085/219740111-a2b093d3-f66f-4d87-9a5e-eed9ff9c370b.jpg)

![System](https://user-images.githubusercontent.com/57676085/219740219-6fec4011-4c99-409e-9931-78ad550a97b3.jpg)

**Comment by JulienHeijmans** [comment]
Alright, thank you for the very detailed answer!
I do not have a mac and cannot repro the issue here, but I will look into the issue and try to figure out what changed in 3.5/3.6

**Comment by nurb2kea** [comment]
I guess this is a good hint from @PratikPB2123

https://projects.blender.org/blender/blender-addons/commit/5c22e77ea30327173d542b41dc2f7653f2cb1a7a
and
https://projects.blender.org/mano-wii

**Comment by nurb2kea** [comment]
[@Nurb2Kea](https://projects.blender.org/Nurb2Kea) it seems like [@Julien-Heijmans](https://projects.blender.org/Julien-Heijmans) is the maintainer of the add-on. You have already been in contact with him.

There are two reasons why shaders needs to be ported:

Addon still uses bgl that call OpenGL calls directly.
Shader don't use gpu.types.ShaderCreateInfo to support cross platform source generation.
These structures have already been in place for some time, and we communicated that addon developers should use this new API. It is sadly common for developers to only port to newer API's when it makes sense for them.

In this case it looks like he hasn't ported his shaders to use gpu.types.ShaderCreateInfo as described on https://docs.blender.org/api/current/gpu.html. If someone requires some help they can get in contact with the Eevee/viewport module at blender.chat or in the python channel. I am happy to help out there.

**Comment by JulienHeijmans** [comment]
Thank you, I will look at that.

**Comment by JulienHeijmans** [comment]
Could you try the latest revision on this branch: https://github.com/JulienHeijmans/quicksnap/tree/update-shader-definition-blender3.5 
It should, I think, fix the crashes due to shader definition.There might be some other causes for crash.
No matter what, if it works you can still expect some warning spam in the console when you use the addon, due to some other deprecated bgl calls. (I will also look at those)

**Comment by nurb2kea** [comment]
Hi,
so when you rename the zip and the installed addon folder to quicksnap, it is installing and working fine again. 
Otherwise you get this:
![Screenshot 2023-02-20 at 8 45 14 pm](https://user-images.githubusercontent.com/57676085/220188587-4d48cd0b-a9aa-48db-9d41-a68e8c508949.jpg)


Thanks for your help and work.
This is one of the important addons I use daily.

**Comment by JulienHeijmans** [comment]
>Otherwise you get this

Ah yes, right, that happens when there is a "." in the name of the zip file, it won't happen when the update is delivered to the users.

> so when you rename the zip and the installed addon folder to quicksnap, it is installing and working fine again.
Thanks for your help and work.
This is one of the important addons I use daily.

Great, happy to have that resolved. To be honest I knew that I used some older APIs, but back then there was very little documentation and I could not update all the code to use the new api. So I am happy that this is fixed once and for all :) 

Thank you for reporting and following up with the information, so other people won't face the same issue as you did.

**Comment by nurb2kea** [comment]
Don't forget to update Blendermarket ...
![Screenshot 2023-02-21 at 12 07 43 am](https://user-images.githubusercontent.com/57676085/220210947-5eb8c3f5-128e-4c81-8f35-ecedb4fe096b.jpg)

**Comment by JulienHeijmans** [comment]
I am not forgetting it. The current fix makes the addon fail to load on blender 3.3 because it uses shaders that did not exist on older blender versions. I need to add code that makes the addon use different shaders based on the blender version. When it is done I will update the addon everywhere.
