### ISSUE TITLE
The snapping is not working!

### ISSUE THREAD

**Issue by WorldsGreatestHobby** [JulienHeijmans/quicksnap#52]
So when you hit Shirt+ctr+V, the plugin opens as it should. But it refuses to snap to the part to move it around! It usually works in object mode but doesn't work at all in edit mode.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/118316068/221712966-8f07d38c-85e5-45a4-a0d3-afe5efac211a.gif)

**Comment by nurb2kea** [comment]
Works for me on macos.
Have you seen the key options 1,2 and 3 to tell if it uses vertex, edge or face !?
Just start the tool and in your case hit the 1 key to select the vertex, and then hit 1 again for the target mesh vertex snap...

**Comment by WorldsGreatestHobby** [comment]
That didn't work. I must be some kind of bug, Idk.

**Comment by nurb2kea** [comment]
Maybe Julian knows the cause of it.
I would uninstall, reboot blender, reinstall and test it, just in case!

**Comment by WorldsGreatestHobby** [comment]
Still didn't work.

**Comment by nurb2kea** [comment]
Try this:
This are my settings and the latest link ready for blender 3.5-3.6 and backwards to 3.3 !
https://github.com/JulienHeijmans/quicksnap/releases/tag/1_4_3
![Screenshot 2023-02-28 at 2 07 53 am](https://user-images.githubusercontent.com/57676085/221726398-9b1d3e42-b0b2-4dee-afb3-2923604fb8aa.jpg)

**Comment by WorldsGreatestHobby** [comment]
Mine are all the same.

**Comment by nurb2kea** [comment]
Hmm, then better wait for Julien's answer.
I tested it only on macos with blender 3.41, 3.5 & 3.6 and it works in in both edit and object mode.
Must be a windows thing !
What quicksnap versions did you install?

Anyways, better wait for his answer!

**Comment by JulienHeijmans** [comment]
Hey! Could you send me your blend file (julien.heijmans@gmail.com, I will delete the file once I am done with your issue)? Also, what version of Quicksnap do you have and what version of Blender are you using?

**Comment by JulienHeijmans** [comment]
Alright, I managed to repro, it looks like a bug managed to slip into the very last version, for now you can get the previous version (video below showing how to do that), I will fix the issue later, hopefully today..

https://user-images.githubusercontent.com/35562774/221821917-b37f123e-b15c-478c-99b4-a798ea6e8eb1.mp4

**Comment by WorldsGreatestHobby** [comment]
Okay!

**Comment by WorldsGreatestHobby** [comment]
Just sent the file

**Comment by JulienHeijmans** [comment]
> Just sent the file
I did not get you email.

Also, did you try with 1.4.2 or 1.4.1 to see if it works there?

**Comment by WorldsGreatestHobby** [comment]
I tried 1.4.2 and 1.4.1 and it didn't seem to work. Also, I think I sent it now.

**Comment by JulienHeijmans** [comment]
Ok, I figured out the issue after looking at your blender file, is seems the addon has some issue when you have multiple objects selected and when you are in edit mode, it only gives you the vertices of the active object as a source of snapping.
I pushed a fix on the main branch.

Could you try now, in the addon preference window, Click on `Install Main/Old version`, (You might need to click `Check for update` before), then in the dropdown, choose `main`. and see how things are going?

**Comment by WorldsGreatestHobby** [comment]
Just loaded up blender and tested it. It worked! Thanks for taking time out of your day to fix this! Have a great day!
