### ISSUE TITLE
error in 4.0

### ISSUE THREAD

**Issue by JimWho** [JulienHeijmans/quicksnap#58]
Traceback (most recent call last):
  File "D:\Blender Foundation\daily\blender-4.0.0-alpha+daily.db43b2722779\4.0\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "D:\Blender Foundation\scripts\addons\quicksnap\__init__.py", line 31, in <module>
    globals()[currentModuleFullName] = importlib.import_module(currentModuleFullName)
  File "D:\Blender Foundation\daily\blender-4.0.0-alpha+daily.db43b2722779\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Blender Foundation\scripts\addons\quicksnap\quicksnap_render.py", line 20, in <module>
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'

blender updates to fast, could you please update to adapt it

**Comment by JulienHeijmans** [comment]
Hey! Thank you for reporting the issue.
Could you try to download the version that is on this branch here:
https://github.com/JulienHeijmans/quicksnap/tree/4-0a-Fix

And tell me how it goes?
Thank you!

**Comment by JimWho** [comment]
While there is no reason to require support for the latest version, the addon seems work well
Thanks !!

**Comment by nurb2kea** [comment]
I tried the the 4-0a-Fix with no luck !
![Screenshot 2023-05-30 at 10 07 06 pm](https://github.com/JulienHeijmans/quicksnap/assets/57676085/4f54a36e-4b3d-449d-80fb-76058b8205c3)

**Comment by JulienHeijmans** [comment]
Could you tell me what is not working? The addon seems to enable at least base on your screenshot. Maybe you could copy/paste the console messages?

**Comment by nurb2kea** [comment]
Hi,
here the terminal output from Intel MacOS Terminal:
  File "/Users/NURB/blender-git/build_darwin/bin/Blender.app/Contents/Resources/4.0/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Applications/BLENDER/ADDONS etc/addons/quicksnap/__init__.py", line 31, in <module>
    globals()[currentModuleFullName] = importlib.import_module(currentModuleFullName)
  File "/Users/NURB/blender-git/build_darwin/bin/Blender.app/Contents/Resources/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Applications/BLENDER/ADDONS etc/addons/quicksnap/quicksnap_render.py", line 20, in <module>
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'




That's what it looks like on Intel MacOS blender 3.6a:

![Screenshot 2023-05-30 at 11 25 36 pm](https://github.com/JulienHeijmans/quicksnap/assets/57676085/75b515ac-cf15-4d25-a45f-c30c3f041c7a)
![System](https://github.com/JulienHeijmans/quicksnap/assets/57676085/c98ecfc2-aa95-4d0c-ae33-af0b3eb9bfd9)

**Comment by nurb2kea** [comment]
Is this what you needed to investigate that quicklook isn't showing up in preferences and viewport?

**Comment by JulienHeijmans** [comment]
4.0 is still just an alpha version, not even beta, you can't expect all addons to update permanently to match Blender versions that might change a lot before they even get completed. Especially from a **free** add-on made by someone during his free time. (With the upcoming birth of my child, the free blender addon is not really on top of my priorities, especially for alpha versions.)

It also looks like addon compilations is made differently on windows machine and on mac machine, as I (And JimWho, that created the issue) am not getting your issue, which makes it harder to fix.

Anyway, I made a new attemps at fixing the addon for 4.0a, could you try getting the latest version on the branch? Here: https://github.com/JulienHeijmans/quicksnap/tree/4-0a-Fix
Could you tell me if it did the trick?

**Comment by nurb2kea** [comment]
Hi,

just tested it quickly with constrains, 1,2,3, etc.
Everything is back on track.

Thank you very much for your support. 
I'm just asking everyone to look after their addon if it has some issues, by providing info, help and hints from the belnder dev.'s, I got and discovered.
So far everyone incl. you fixed their addon already, because 'most' breaking changes already been done by the blender team for 4.0, in this area of displaying the HUD from the addon again, getting it regisered correctly,... 
Most of them are happy to have me for mac issues to test and help.

I understand that you a are maybe a bit grumpy and not happy like the other ones about the situation and you're right. 
But I didn't know your background.

Anyways, a BIG thank you for your support and time.
I wish you and your family all the best for the big upcoming day! :-)
I stop here, so you can take a sleep before it's to late... :-)

King regards

Guido

![Screenshot 2023-06-10 at 3 22 58 pm](https://github.com/JulienHeijmans/quicksnap/assets/57676085/fe9d19e2-5796-46e5-ac36-517c6c607302)

**Comment by nurb2kea** [comment]
Do you put version 1.4.5 to the release page?
