### ISSUE TITLE
Snapping

### ISSUE THREAD

**Issue by LukaCub** [JulienHeijmans/quicksnap#6]
I'm sending a video where it can be seen that I can't catch any vertex point and when it shows me it is far enough from the vertex and when I press the left mouse button, it deactivates. I used Blender 3.2
![blender_1yJyzq0yW1](https://user-images.githubusercontent.com/59843425/195019883-c2f153f3-6d75-48dc-a1e3-cb2fdb180a58.gif)

**Comment by LukaCub** [comment]
Thank you very much, I will try to test it

**Comment by LukaCub** [comment]
Ok, I tried it and it works perfectly. Thanks!

**Comment by JulienHeijmans** [comment]
Super, happy to hear that! :)

I am now closing the issue. Thanks again for reporting the problem!
