### ISSUE TITLE
Blender 4.1 - QuickSnap 1.4.5 last version - EdgeMid Points Issue

### ISSUE THREAD

**Issue by nehalllem** [JulienHeijmans/quicksnap#70]
![Screenshot_1111](https://github.com/JulienHeijmans/quicksnap/assets/113052680/ee06c718-5ab7-49b3-82ac-92fc37777a9d)

Hi=) When I switch to mode 2 (edge midpoints) an error appears. On the screen there is an artifact square from the addon. and the quick menu remains on top.

**Comment by JulienHeijmans** [comment]
Hi! Thank you for reporting the issue, could you try out the version here and tell me it fixes the issue? 
https://github.com/JulienHeijmans/quicksnap/tree/4-0a-Fix ([Download Link](https://github.com/JulienHeijmans/quicksnap/archive/refs/heads/4-0a-Fix.zip))

**Comment by nehalllem** [comment]
No=( same issue

![Screenshot_2222](https://github.com/JulienHeijmans/quicksnap/assets/113052680/900e934f-403b-4551-90e0-0d1205dfd8cb)
