### ISSUE TITLE
Toggle activating the tool vertex mode

### ISSUE THREAD

**Issue by LatrochS** [JulienHeijmans/quicksnap#8]
Hi, i installed the add-on and the first time to try it, i just selected the object you see active in the screenshot and want to move it just to try how it works. but the error is like you see in screenshot appears when i enable quicksnape to move objects i followed the instructions you gave us how to use. thank you.

![Screenshot 2022-10-12 082037](https://user-images.githubusercontent.com/111054260/195265991-921becc2-24da-4c21-945c-c0d973297f4a.png)

**Comment by JulienHeijmans** [comment]
Hi!
Thank you for very much for creating the issue.

I will have a look at the code and try to figure out what is happening.
This is the first time I see that issue, I am suspecting there is something in the scene that the add-on was not expecting. Would it be possible for you to send me the blender file? (to me email : julien.heijmans@gmail.com, I would delete the file and the email the moment I fix the issue)

**Comment by JulienHeijmans** [comment]
Hi, thank you for reporting hte issue, aftwe looking at it, I think I have found the origin of the problem, I will make a fix. In the meantime, you can set in the add on settings the option "Snap from/to object origins" to Always ON.
![image](https://user-images.githubusercontent.com/35562774/195275909-6d8e6180-256f-489e-814a-9f1323ad8bc7.png)

I will try to make a fix for that issue.

**Comment by LatrochS** [comment]
Hi, thank you for the update but an other problem showed up.
the active object snap to it own vertex only and own origin also in edit mode same thing it can't detect other mechs. thank you.

https://user-images.githubusercontent.com/111054260/195301313-a44216e2-82ec-420f-86c9-c1485a31c71c.mp4

**Comment by LatrochS** [comment]
haa nice okay i understand sorry my bad. Thank you.
